// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_gibasa_RCPPEXPORTS_H_GEN_
#define RCPP_gibasa_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace gibasa {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("gibasa", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("gibasa", "_gibasa_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in gibasa");
            }
        }
    }

    inline Rcpp::DataFrame posParallelRcpp(std::vector<std::string> text, std::string sys_dic, std::string user_dic) {
        typedef SEXP(*Ptr_posParallelRcpp)(SEXP,SEXP,SEXP);
        static Ptr_posParallelRcpp p_posParallelRcpp = NULL;
        if (p_posParallelRcpp == NULL) {
            validateSignature("Rcpp::DataFrame(*posParallelRcpp)(std::vector<std::string>,std::string,std::string)");
            p_posParallelRcpp = (Ptr_posParallelRcpp)R_GetCCallable("gibasa", "_gibasa_posParallelRcpp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_posParallelRcpp(Shield<SEXP>(Rcpp::wrap(text)), Shield<SEXP>(Rcpp::wrap(sys_dic)), Shield<SEXP>(Rcpp::wrap(user_dic)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::DataFrame >(rcpp_result_gen);
    }

}

#endif // RCPP_gibasa_RCPPEXPORTS_H_GEN_
