// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/gibasa.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dict_index_sys
bool dict_index_sys(const std::string& dic_dir, const std::string& out_dir, const std::string& encoding);
static SEXP _gibasa_dict_index_sys_try(SEXP dic_dirSEXP, SEXP out_dirSEXP, SEXP encodingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type dic_dir(dic_dirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_dir(out_dirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type encoding(encodingSEXP);
    rcpp_result_gen = Rcpp::wrap(dict_index_sys(dic_dir, out_dir, encoding));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_dict_index_sys(SEXP dic_dirSEXP, SEXP out_dirSEXP, SEXP encodingSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_dict_index_sys_try(dic_dirSEXP, out_dirSEXP, encodingSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dict_index_user
bool dict_index_user(const std::string& dic_dir, const std::string& file, const std::string& csv_file, const std::string& encoding);
static SEXP _gibasa_dict_index_user_try(SEXP dic_dirSEXP, SEXP fileSEXP, SEXP csv_fileSEXP, SEXP encodingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type dic_dir(dic_dirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type file(fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type csv_file(csv_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type encoding(encodingSEXP);
    rcpp_result_gen = Rcpp::wrap(dict_index_user(dic_dir, file, csv_file, encoding));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_dict_index_user(SEXP dic_dirSEXP, SEXP fileSEXP, SEXP csv_fileSEXP, SEXP encodingSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_dict_index_user_try(dic_dirSEXP, fileSEXP, csv_fileSEXP, encodingSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dictionary_info
Rcpp::DataFrame dictionary_info(const std::string& sys_dic, const std::string& user_dic);
static SEXP _gibasa_dictionary_info_try(SEXP sys_dicSEXP, SEXP user_dicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type sys_dic(sys_dicSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type user_dic(user_dicSEXP);
    rcpp_result_gen = Rcpp::wrap(dictionary_info(sys_dic, user_dic));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_dictionary_info(SEXP sys_dicSEXP, SEXP user_dicSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_dictionary_info_try(sys_dicSEXP, user_dicSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// transition_cost
int transition_cost(unsigned short rcAttr, unsigned short lcAttr, const std::string& sys_dic, const std::string& user_dic);
static SEXP _gibasa_transition_cost_try(SEXP rcAttrSEXP, SEXP lcAttrSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< unsigned short >::type rcAttr(rcAttrSEXP);
    Rcpp::traits::input_parameter< unsigned short >::type lcAttr(lcAttrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sys_dic(sys_dicSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type user_dic(user_dicSEXP);
    rcpp_result_gen = Rcpp::wrap(transition_cost(rcAttr, lcAttr, sys_dic, user_dic));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_transition_cost(SEXP rcAttrSEXP, SEXP lcAttrSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_transition_cost_try(rcAttrSEXP, lcAttrSEXP, sys_dicSEXP, user_dicSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// posDebugRcpp
Rcpp::DataFrame posDebugRcpp(const std::vector<std::string>& text, const std::string& sys_dic, const std::string& user_dic, Rcpp::LogicalVector partial);
static SEXP _gibasa_posDebugRcpp_try(SEXP textSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP, SEXP partialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type text(textSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sys_dic(sys_dicSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type user_dic(user_dicSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type partial(partialSEXP);
    rcpp_result_gen = Rcpp::wrap(posDebugRcpp(text, sys_dic, user_dic, partial));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_posDebugRcpp(SEXP textSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP, SEXP partialSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_posDebugRcpp_try(textSEXP, sys_dicSEXP, user_dicSEXP, partialSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// posParallelRcpp
Rcpp::DataFrame posParallelRcpp(const std::vector<std::string>& text, const std::string& sys_dic, const std::string& user_dic, Rcpp::LogicalVector partial, const std::size_t& grain_size);
static SEXP _gibasa_posParallelRcpp_try(SEXP textSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP, SEXP partialSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type text(textSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sys_dic(sys_dicSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type user_dic(user_dicSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type partial(partialSEXP);
    Rcpp::traits::input_parameter< const std::size_t& >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(posParallelRcpp(text, sys_dic, user_dic, partial, grain_size));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _gibasa_posParallelRcpp(SEXP textSEXP, SEXP sys_dicSEXP, SEXP user_dicSEXP, SEXP partialSEXP, SEXP grain_sizeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_gibasa_posParallelRcpp_try(textSEXP, sys_dicSEXP, user_dicSEXP, partialSEXP, grain_sizeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _gibasa_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("bool(*dict_index_sys)(const std::string&,const std::string&,const std::string&)");
        signatures.insert("bool(*dict_index_user)(const std::string&,const std::string&,const std::string&,const std::string&)");
        signatures.insert("Rcpp::DataFrame(*dictionary_info)(const std::string&,const std::string&)");
        signatures.insert("int(*transition_cost)(unsigned short,unsigned short,const std::string&,const std::string&)");
        signatures.insert("Rcpp::DataFrame(*posDebugRcpp)(const std::vector<std::string>&,const std::string&,const std::string&,Rcpp::LogicalVector)");
        signatures.insert("Rcpp::DataFrame(*posParallelRcpp)(const std::vector<std::string>&,const std::string&,const std::string&,Rcpp::LogicalVector,const std::size_t&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _gibasa_RcppExport_registerCCallable() { 
    R_RegisterCCallable("gibasa", "_gibasa_dict_index_sys", (DL_FUNC)_gibasa_dict_index_sys_try);
    R_RegisterCCallable("gibasa", "_gibasa_dict_index_user", (DL_FUNC)_gibasa_dict_index_user_try);
    R_RegisterCCallable("gibasa", "_gibasa_dictionary_info", (DL_FUNC)_gibasa_dictionary_info_try);
    R_RegisterCCallable("gibasa", "_gibasa_transition_cost", (DL_FUNC)_gibasa_transition_cost_try);
    R_RegisterCCallable("gibasa", "_gibasa_posDebugRcpp", (DL_FUNC)_gibasa_posDebugRcpp_try);
    R_RegisterCCallable("gibasa", "_gibasa_posParallelRcpp", (DL_FUNC)_gibasa_posParallelRcpp_try);
    R_RegisterCCallable("gibasa", "_gibasa_RcppExport_validate", (DL_FUNC)_gibasa_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_gibasa_dict_index_sys", (DL_FUNC) &_gibasa_dict_index_sys, 3},
    {"_gibasa_dict_index_user", (DL_FUNC) &_gibasa_dict_index_user, 4},
    {"_gibasa_dictionary_info", (DL_FUNC) &_gibasa_dictionary_info, 2},
    {"_gibasa_transition_cost", (DL_FUNC) &_gibasa_transition_cost, 4},
    {"_gibasa_posDebugRcpp", (DL_FUNC) &_gibasa_posDebugRcpp, 4},
    {"_gibasa_posParallelRcpp", (DL_FUNC) &_gibasa_posParallelRcpp, 5},
    {"_gibasa_RcppExport_registerCCallable", (DL_FUNC) &_gibasa_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_gibasa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
