# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install MeCab
        run: |
          git clone --depth=1 https://github.com/taku910/mecab.git
          cd mecab/mecab
          ./configure --enable-utf8-only
          make
          sudo make install
          cd ../mecab-ipadic
          ./configure --with-charset=utf8
          make
          sudo make install
          cd ../../

      - name: Japanese fonts
        run: sudo apt install fonts-ipafont fonts-ipaexfont

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::sessioninfo
            any::stringr
            any::styler
            any::ggdendro
            any::ggpubr
            any::quanteda
            any::quanteda.textmodels
            any::quanteda.textplots
            any::quanteda.textstats
            any::RcppSimdJson
            any::reactable
            any::textmineR
            any::textrecipes
            any::tidymodels
            any::topicmodels
            any::uwot
            any::xgboost
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'install.packages("ldccr", repos = "https://paithiov909.r-universe.dev")'
          Rscript -e 'pkgdown::deploy_to_branch(install = TRUE)'
